## Nummy array and basics

In [4]:
import numpy as np

## creating array from list

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)

arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr_2D)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


## List vs nupy array

In [ ]:
py_list = [1,2,3]
print("python list multiplication", py_list * 2)

np_array = np.array([1,2,3])  # element wise multipication
print("python array multiplication", np_array * 2)


python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]


In [ ]:
np_array = np.arange(25)
# np_array = np.arange(250000)
np_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## creating arrays from scratch

In [20]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full = np.full((2,4), 7)
print("constants \n",full)

random = np.random.random((2,3))
print("\n",random)

sequence = np.arange(0,10,2)
print("Sequence \n", sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
constants 
 [[7 7 7 7]
 [7 7 7 7]]

 [[0.80102003 0.0727922  0.50611992]
 [0.5625938  0.88473956 0.93188929]]
Sequence 
 [0 2 4 6 8]


## vector, matrix and tensor

In [ ]:
vector = np.array([1,2,3])

print("Vector", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1,2], [3,4]],               # 3D
                   [[5,6],[7,8]]])
print("Tensor: \n", tensor)


Vector [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties

In [28]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("size ", arr.size)
print("Dtype", arr.dtype)

Shape  (2, 3)
Dimension  2
size  6
Dtype int64


## Array reshaping

In [34]:
arr = np.arange(12)
print("Original array", arr)

reshaped = arr.reshape((3,4))
print("reshaped array", reshaped)

flattened = reshaped.flatten()
print("Flattened array", flattened)

# ravel (returns view instead of copy).   means returns original data instead of its updated copy

raveled = reshaped.ravel()
print("raveled array", raveled)

# Transpose
transpose = reshaped.T
print("Transpose: \n", transpose)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
