## Numpy Array operations

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing: ", arr[2:7])
print("with step", arr[1:8:2])
print("negative indexing", arr[-3])

basic slicing:  [3 4 5 6 7]
with step [2 4 6 8]
negative indexing 8


In [4]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("specific element", arr_2d[1,2])
print("entire row", arr_2d[1])
print("entire coloumn", arr_2d[:,2])

specific element 6
entire row [4 5 6]
entire coloumn [3 6 9]


# Sorting

In [ ]:
unsorted= np.array([3,5,1,7,3,6,2])
print("Sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2], [2,3]])
print("sorted 2d array", np.sort(arr_2d_unsorted, axis = 1))  #row wise sorted


Sorted array [1 2 3 3 5 6 7]
sorted 2d array [[1 3]
 [1 2]
 [2 3]]


## Filter

In [8]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0] # numpy allows to write conditions or expressions too in this position

print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [10]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [12]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where", numbers[where_result])

[1 3 5]
NP where [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, "true", "false")     # x and y parameter given with condition        it return x if condition is fullfiled instead of real element      (used for measuring majority voting example)
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [ ]:
# above line can be summarized as 

# if(numbers > 5){
#     true
# } else {
#     false
# }

## Adding and removing data

In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2
print(combined)
combined2 = np.concatenate((arr1, arr2))
print(combined2)

[5 7 9]
[1 2 3 4 5 6]


## array compatibility

In [19]:
a= np.array([1,2,3,])
b= np.array([4,5,6])
c = np.array([7,8,9,10])

print("compatability shapes", a.shape == b.shape)
print("compatability shapes", b.shape == c.shape)

compatability shapes True
compatability shapes False


In [ ]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("\n",with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]

 [[1 2 7]
 [3 4 8]]


In [24]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print(deleted)

[1 2 4 5]
